version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - apt install -y nginx

  build:
    commands:
      - mkdir -p /var/www/html
      - cp index.html /var/www/html/
      - nginx -g 'daemon off;' &  # Starts Nginx in the background

artifacts:
  files:
    - '**/*'
  base-directory: /var/www/html
  name: nginx-artifact
